//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Filename 的本地化字符串。
        /// </summary>
        public static string Basic_Info_Filename {
            get {
                return ResourceManager.GetString("Basic_Info_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File size 的本地化字符串。
        /// </summary>
        public static string Basic_Info_Filesize {
            get {
                return ResourceManager.GetString("Basic_Info_Filesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Info 的本地化字符串。
        /// </summary>
        public static string Basic_Info_Image_Info {
            get {
                return ResourceManager.GetString("Basic_Info_Image_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified Date 的本地化字符串。
        /// </summary>
        public static string Basic_Info_Modified_Date {
            get {
                return ResourceManager.GetString("Basic_Info_Modified_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ask 的本地化字符串。
        /// </summary>
        public static string BehaviorOnReachingFirstLastFile_Ask {
            get {
                return ResourceManager.GetString("BehaviorOnReachingFirstLastFile_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goto previous or next folder 的本地化字符串。
        /// </summary>
        public static string BehaviorOnReachingFirstLastFile_GotoPreviousNextFolder {
            get {
                return ResourceManager.GetString("BehaviorOnReachingFirstLastFile_GotoPreviousNextFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loop in current folder 的本地化字符串。
        /// </summary>
        public static string BehaviorOnReachingFirstLastFile_LoopInFolder {
            get {
                return ResourceManager.GetString("BehaviorOnReachingFirstLastFile_LoopInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do nothing 的本地化字符串。
        /// </summary>
        public static string BehaviorOnReachingFirstLastFile_Stop {
            get {
                return ResourceManager.GetString("BehaviorOnReachingFirstLastFile_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Mode 的本地化字符串。
        /// </summary>
        public static string Context_ViewMode {
            get {
                return ResourceManager.GetString("Context_ViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center big image 的本地化字符串。
        /// </summary>
        public static string Context_ViewMode_CenterBig {
            get {
                return ResourceManager.GetString("Context_ViewMode_CenterBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit window 的本地化字符串。
        /// </summary>
        public static string Context_ViewMode_Fit {
            get {
                return ResourceManager.GetString("Context_ViewMode_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original size 的本地化字符串。
        /// </summary>
        public static string Context_ViewMode_Org {
            get {
                return ResourceManager.GetString("Context_ViewMode_Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stretch small image 的本地化字符串。
        /// </summary>
        public static string Context_ViewMode_StretchSmall {
            get {
                return ResourceManager.GetString("Context_ViewMode_StretchSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string ContextMenu_About {
            get {
                return ResourceManager.GetString("ContextMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string ContextMenu_Exit {
            get {
                return ResourceManager.GetString("ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort image by 的本地化字符串。
        /// </summary>
        public static string ContextMenu_ImgSort {
            get {
                return ResourceManager.GetString("ContextMenu_ImgSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Descending sort 的本地化字符串。
        /// </summary>
        public static string ContextMenu_ImgSort_Desc {
            get {
                return ResourceManager.GetString("ContextMenu_ImgSort_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name 的本地化字符串。
        /// </summary>
        public static string ContextMenu_ImgSort_Filename {
            get {
                return ResourceManager.GetString("ContextMenu_ImgSort_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified date 的本地化字符串。
        /// </summary>
        public static string ContextMenu_ImgSort_ModifiedDate {
            get {
                return ResourceManager.GetString("ContextMenu_ImgSort_ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File size 的本地化字符串。
        /// </summary>
        public static string ContextMenu_ImgSort_Size {
            get {
                return ResourceManager.GetString("ContextMenu_ImgSort_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string ContextMenu_Open {
            get {
                return ResourceManager.GetString("ContextMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string ContextMenu_Settings {
            get {
                return ResourceManager.GetString("ContextMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit window size 的本地化字符串。
        /// </summary>
        public static string DefaultImageDisplayMode_FitWindow {
            get {
                return ResourceManager.GetString("DefaultImageDisplayMode_FitWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In original size 的本地化字符串。
        /// </summary>
        public static string DefaultImageDisplayMode_OriginalSize {
            get {
                return ResourceManager.GetString("DefaultImageDisplayMode_OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same as last time 的本地化字符串。
        /// </summary>
        public static string DefaultWindowMode_LastTime {
            get {
                return ResourceManager.GetString("DefaultWindowMode_LastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximized 的本地化字符串。
        /// </summary>
        public static string DefaultWindowMode_Maximized {
            get {
                return ResourceManager.GetString("DefaultWindowMode_Maximized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string DefaultWindowMode_Normal {
            get {
                return ResourceManager.GetString("DefaultWindowMode_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apeture Value 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Apeture_Value {
            get {
                return ResourceManager.GetString("Exif_Info_Apeture_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exposure Bias Value 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Exposure_Bias_Value {
            get {
                return ResourceManager.GetString("Exif_Info_Exposure_Bias_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExposureTime 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Exposure_Time {
            get {
                return ResourceManager.GetString("Exif_Info_Exposure_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Flash {
            get {
                return ResourceManager.GetString("Exif_Info_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Focal Length 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Focal_Length {
            get {
                return ResourceManager.GetString("Exif_Info_Focal_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISO Speed Ratings 的本地化字符串。
        /// </summary>
        public static string Exif_Info_ISO_Speed_Ratings {
            get {
                return ResourceManager.GetString("Exif_Info_ISO_Speed_Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maker 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Maker {
            get {
                return ResourceManager.GetString("Exif_Info_Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metering Mode 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Metering_Mode {
            get {
                return ResourceManager.GetString("Exif_Info_Metering_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Model {
            get {
                return ResourceManager.GetString("Exif_Info_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        public static string EXIFInfo_Hide {
            get {
                return ResourceManager.GetString("EXIFInfo_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string EXIFInfo_Show {
            get {
                return ResourceManager.GetString("EXIFInfo_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        public static string FileInfo_Hide {
            get {
                return ResourceManager.GetString("FileInfo_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string FileInfo_Show {
            get {
                return ResourceManager.GetString("FileInfo_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show when hover 的本地化字符串。
        /// </summary>
        public static string FileInfo_ShowOnHover {
            get {
                return ResourceManager.GetString("FileInfo_ShowOnHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NNEDI3 的本地化字符串。
        /// </summary>
        public static string ImageDoublingAlgorithm_Nnedi3 {
            get {
                return ResourceManager.GetString("ImageDoublingAlgorithm_Nnedi3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string ImageDoublingAlgorithm_None {
            get {
                return ResourceManager.GetString("ImageDoublingAlgorithm_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bicubic 的本地化字符串。
        /// </summary>
        public static string ImageEnlargingAlgorithm_Bicubic {
            get {
                return ResourceManager.GetString("ImageEnlargingAlgorithm_Bicubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilinear 的本地化字符串。
        /// </summary>
        public static string ImageEnlargingAlgorithm_Bilinear {
            get {
                return ResourceManager.GetString("ImageEnlargingAlgorithm_Bilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bicubic (Prefiltered) 的本地化字符串。
        /// </summary>
        public static string ImageEnlargingAlgorithm_HighQualityBicubic {
            get {
                return ResourceManager.GetString("ImageEnlargingAlgorithm_HighQualityBicubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilinear (Prefiltered) 的本地化字符串。
        /// </summary>
        public static string ImageEnlargingAlgorithm_HighQualityBilinear {
            get {
                return ResourceManager.GetString("ImageEnlargingAlgorithm_HighQualityBilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nearest neighbor 的本地化字符串。
        /// </summary>
        public static string ImageEnlargingAlgorithm_NearestNeighbor {
            get {
                return ResourceManager.GetString("ImageEnlargingAlgorithm_NearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string ImageEnlargingAlgorithm_System {
            get {
                return ResourceManager.GetString("ImageEnlargingAlgorithm_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bicubic 的本地化字符串。
        /// </summary>
        public static string ImageShrinkingAlgorithm_Bicubic {
            get {
                return ResourceManager.GetString("ImageShrinkingAlgorithm_Bicubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilinear 的本地化字符串。
        /// </summary>
        public static string ImageShrinkingAlgorithm_Bilinear {
            get {
                return ResourceManager.GetString("ImageShrinkingAlgorithm_Bilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bicubic (Prefiltered) 的本地化字符串。
        /// </summary>
        public static string ImageShrinkingAlgorithm_HighQualityBicubic {
            get {
                return ResourceManager.GetString("ImageShrinkingAlgorithm_HighQualityBicubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilinear (Prefiltered) 的本地化字符串。
        /// </summary>
        public static string ImageShrinkingAlgorithm_HighQualityBilinear {
            get {
                return ResourceManager.GetString("ImageShrinkingAlgorithm_HighQualityBilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nearest neighbor 的本地化字符串。
        /// </summary>
        public static string ImageShrinkingAlgorithm_NearestNeighbor {
            get {
                return ResourceManager.GetString("ImageShrinkingAlgorithm_NearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        public static string ImageShrinkingAlgorithm_System {
            get {
                return ResourceManager.GetString("ImageShrinkingAlgorithm_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name 的本地化字符串。
        /// </summary>
        public static string SortFileBy_FileName {
            get {
                return ResourceManager.GetString("SortFileBy_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified date 的本地化字符串。
        /// </summary>
        public static string SortFileBy_ModifiedDate {
            get {
                return ResourceManager.GetString("SortFileBy_ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File size 的本地化字符串。
        /// </summary>
        public static string SortFileBy_Size {
            get {
                return ResourceManager.GetString("SortFileBy_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any File 的本地化字符串。
        /// </summary>
        public static string Type_Any {
            get {
                return ResourceManager.GetString("Type_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AVIF Image 的本地化字符串。
        /// </summary>
        public static string Type_AVIF {
            get {
                return ResourceManager.GetString("Type_AVIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BMP Image 的本地化字符串。
        /// </summary>
        public static string Type_BMP {
            get {
                return ResourceManager.GetString("Type_BMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executable 的本地化字符串。
        /// </summary>
        public static string Type_EXE {
            get {
                return ResourceManager.GetString("Type_EXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FLIF Image 的本地化字符串。
        /// </summary>
        public static string Type_FLIF {
            get {
                return ResourceManager.GetString("Type_FLIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HEIF Image 的本地化字符串。
        /// </summary>
        public static string Type_HEIF {
            get {
                return ResourceManager.GetString("Type_HEIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JPEG Image 的本地化字符串。
        /// </summary>
        public static string Type_JPG {
            get {
                return ResourceManager.GetString("Type_JPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG Image 的本地化字符串。
        /// </summary>
        public static string Type_PNG {
            get {
                return ResourceManager.GetString("Type_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TIFF Image 的本地化字符串。
        /// </summary>
        public static string Type_TIF {
            get {
                return ResourceManager.GetString("Type_TIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WEBP Image 的本地化字符串。
        /// </summary>
        public static string Type_WEBP {
            get {
                return ResourceManager.GetString("Type_WEBP", resourceCulture);
            }
        }
    }
}
