//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Filename 的本地化字符串。
        /// </summary>
        public static string Basic_Info_Filename {
            get {
                return ResourceManager.GetString("Basic_Info_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File size 的本地化字符串。
        /// </summary>
        public static string Basic_Info_Filesize {
            get {
                return ResourceManager.GetString("Basic_Info_Filesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Info 的本地化字符串。
        /// </summary>
        public static string Basic_Info_Image_Info {
            get {
                return ResourceManager.GetString("Basic_Info_Image_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified Date 的本地化字符串。
        /// </summary>
        public static string Basic_Info_Modified_Date {
            get {
                return ResourceManager.GetString("Basic_Info_Modified_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string ContextMenu_Exit {
            get {
                return ResourceManager.GetString("ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string ContextMenu_Open {
            get {
                return ResourceManager.GetString("ContextMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apeture Value 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Apeture_Value {
            get {
                return ResourceManager.GetString("Exif_Info_Apeture_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exposure Bias Value 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Exposure_Bias_Value {
            get {
                return ResourceManager.GetString("Exif_Info_Exposure_Bias_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExposureTime 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Exposure_Time {
            get {
                return ResourceManager.GetString("Exif_Info_Exposure_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Flash {
            get {
                return ResourceManager.GetString("Exif_Info_Flash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Focal Length 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Focal_Length {
            get {
                return ResourceManager.GetString("Exif_Info_Focal_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISO Speed Ratings 的本地化字符串。
        /// </summary>
        public static string Exif_Info_ISO_Speed_Ratings {
            get {
                return ResourceManager.GetString("Exif_Info_ISO_Speed_Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maker 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Maker {
            get {
                return ResourceManager.GetString("Exif_Info_Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metering Mode 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Metering_Mode {
            get {
                return ResourceManager.GetString("Exif_Info_Metering_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model 的本地化字符串。
        /// </summary>
        public static string Exif_Info_Model {
            get {
                return ResourceManager.GetString("Exif_Info_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Any File 的本地化字符串。
        /// </summary>
        public static string Type_Any {
            get {
                return ResourceManager.GetString("Type_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HEIF Image 的本地化字符串。
        /// </summary>
        public static string Type_HEIF {
            get {
                return ResourceManager.GetString("Type_HEIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG Image 的本地化字符串。
        /// </summary>
        public static string Type_PNG {
            get {
                return ResourceManager.GetString("Type_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WEBP Image 的本地化字符串。
        /// </summary>
        public static string Type_WEBP {
            get {
                return ResourceManager.GetString("Type_WEBP", resourceCulture);
            }
        }
    }
}
